
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_AXI_BTN_DEVICE_ID,
		XPAR_AXI_BTN_BASEADDR,
		XPAR_AXI_BTN_INTERRUPT_PRESENT,
		XPAR_AXI_BTN_IS_DUAL
	},
	{
		XPAR_AXI_LED_DEVICE_ID,
		XPAR_AXI_LED_BASEADDR,
		XPAR_AXI_LED_INTERRUPT_PRESENT,
		XPAR_AXI_LED_IS_DUAL
	}
};


