# HI-Speed
set_property PACKAGE_PIN V15 [get_pins {io_pmod_jc[0]}]
set_property PACKAGE_PIN W15 [get_pins {io_pmod_jc[1]}]
set_property PACKAGE_PIN T11 [get_pins {io_pmod_jc[2]}]
set_property PACKAGE_PIN T10 [get_pins {io_pmod_jc[3]}]
set_property PACKAGE_PIN W14 [get_pins {io_pmod_jc[4]}]
set_property PACKAGE_PIN Y14 [get_pins {io_pmod_jc[5]}]
set_property PACKAGE_PIN T12 [get_pins {io_pmod_jc[6]}]
set_property PACKAGE_PIN U12 [get_pins {io_pmod_jc[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports io_pmod_jc*]
